#+TITLE: Homework 6
#+AUTHOR: Elizabeth Hunt
#+LATEX_HEADER: \notindent \notag  \usepackage{amsmath} \usepackage[a4paper,margin=1in,portrait]{geometry}
#+LATEX: \setlength\parindent{0pt}
#+OPTIONS: toc:nil

* Question One
See ~UTEST(eigen, dominant_eigenvalue)~ in ~test/eigen.t.c~ and the entry
~Eigen-Adjacent -> dominant_eigenvalue~ in the LIZFCM API documentation.
* Question Two
See ~UTEST(eigen, leslie_matrix_dominant_eigenvalue)~ in ~test/eigen.t.c~
and the entry ~Eigen-Adjacent -> leslie_matrix~ in the LIZFCM API
documentation.
* Question Three
See ~UTEST(eigen, least_dominant_eigenvalue)~ in ~test/eigen.t.c~ which
finds the least dominant eigenvalue on the matrix:

\begin{bmatrix}
2 & 2 & 4 \\
1 & 4 & 7 \\
0 & 2 & 6 
\end{bmatrix}

which has eigenvalues: $5 + \sqrt{17}, 2, 5 - \sqrt{17}$ and should thus produce $5 - \sqrt{17}$.

See also the entry ~Eigen-Adjacent -> least_dominant_eigenvalue~ in the LIZFCM API
documentation.
* Question Four
See ~UTEST(eigen, shifted_eigenvalue)~ in ~test/eigen.t.c~ which
finds the least dominant eigenvalue on the matrix:

\begin{bmatrix}
2 & 2 & 4 \\
1 & 4 & 7 \\
0 & 2 & 6 
\end{bmatrix}

which has eigenvalues: $5 + \sqrt{17}, 2, 5 - \sqrt{17}$ and should thus produce $2.0$.

With the initial guess: $[0.5, 1.0, 0.75]$.

See also the entry ~Eigen-Adjacent -> shift_inverse_power_eigenvalue~ in the LIZFCM API
documentation.
* Question Five
See ~UTEST(eigen, partition_find_eigenvalues)~ in ~test/eigen.t.c~ which
finds the eigenvalues in a partition of 10 on the matrix:

\begin{bmatrix}
2 & 2 & 4 \\
1 & 4 & 7 \\
0 & 2 & 6 
\end{bmatrix}

which has eigenvalues: $5 + \sqrt{17}, 2, 5 - \sqrt{17}$, and should produce all three from
the partitions when given the guesses $[0.5, 1.0, 0.75]$ from the questions above.

See also the entry ~Eigen-Adjacent -> partition_find_eigenvalues~ in the LIZFCM API
documentation.

* Question Six

